spring.application.name=backend
server.port=8080
server.error.include-message=never

spring.datasource.url=jdbc:postgresql://localhost:5432/payflowdb
spring.datasource.username=payflowdb
spring.datasource.password=241616
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.open-in-view=false
spring.jackson.default-property-inclusion=non_null
security.jwt.secret=${PAYFLOW_JWT_SECRET:change-this-development-secret-to-a-random-32-byte-value}
security.jwt.expiry=PT30M
